### ISSUE TITLE
AttributeError: 'Namespace' object has no attribute 'num_ngrams_fdg' after installing

### ISSUE THREAD

**Issue by Jack-Lewis1** [datasciencecampus/pygrams#372]
I `Successfully installed pyGrams` then I tried to run `python pygrams.py -ds=USPTO-random-10000.pkl.bz2` but I ran into this error. 

```C:\Users\My_name\Documents\pygrams>python pygrams.py -ds=USPTO-random-10000.pkl.bz2
C:\Users\My_name\Anaconda3\envs\pygrams_env\lib\site-packages\gensim\utils.py:1197: UserWarning: detected Windows; aliasing chunkize to chunkize_serial
  warnings.warn("detected Windows; aliasing chunkize to chunkize_serial")

WARNING: No dates defined - time series analysis will not be possible with the cached object!

Traceback (most recent call last):
  File "pygrams.py", line 261, in <module>
    main(sys.argv[1:])
  File "pygrams.py", line 157, in main
    argscheck.checkargs()
  File "C:\Users\My_name\Documents\pygrams\scripts\utils\argschecker.py", line 95, in checkargs
    if self.args.num_ngrams_fdg < 10:
AttributeError: 'Namespace' object has no attribute 'num_ngrams_fdg'

```

I set this up into an anaconda environment with python 3.6. I used git clone to install the repo.

**Comment by mshodge** [comment]
Hi @Jack-Lewis1 we will fix this shortly. Thanks for flagging.

**Comment by Jack-Lewis1** [comment]
Hey. Was this fixed? @mshodge

**Comment by mshodge** [comment]
Hey sorry @Jack-Lewis1 busy period for us at the moment, I've issued a Pull Request #373 and am just waiting on someone else on the project to review and merge.
